### ISSUE TITLE
Implement sampler widget

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#1326]
## Objective

Implement the (Component) Sampler widget.

## Background
![component-sampler](https://user-images.githubusercontent.com/12857772/50574046-51ef8d80-0de0-11e9-8232-39acadca2736.jpg)

**Comment by matthiasrohmer** [comment]
I started implementing the frontend for this widget on `feature/component-sampler` (see http://localhost:8080/documentation/components/A/amp-amp.html) though the layout changed since then. I need to check with Longo what his plans were.

![component-sampler-2](https://user-images.githubusercontent.com/12857772/50587796-a6961580-0e7f-11e9-8295-35a12c904c9c.jpg)

Now for the functionality part: when I was building the frontend I had the simplest implementation in mind and thought that the source code preview will be prerendered and already be in the DOM and the preview will be inside an `amp-iframe` whose `src` attribute will be toggled on click on one of the tabs.

@sebastianbenz, what do you think? There are plenty of other ways of doing it and I don't really have a strong opinion on which route to go. Might also be that we have already discussed it but I cant find any hints in my notes so I would greatly appreciate your thoughts on this 🙂

**Comment by sebastianbenz** [comment]
I see two ways to implement this:

1. The whole component sampler is embedded via an amp-iframe. 
2. source code is prerendered and preview is embedded (as you suggested)

### Discussion

1. Is easiest to implement as it's just another sample template. We'd need a good placeholder though. This would be my suggested path forward.
2. Offers a better UX due to pre-rendering, but is harder to implement as it means we have to generate multiple preview files from each single sample source file. It's not particularly hard, but just needs another separate build step.

### Crazy idea

We could use the playground for this (we need an embeddable version anyway for the homepage). This would just require splitting the sample files into multiple ones as in 2. Each tab would then embed the playground in an amp-iframe via `/playground/embed?url=/samples/components/amp-img/embed/1`. 

### Open Questions

* Each sample tab has additional documentation. How do we want to integrate it?
* How do you plan to embed the component sampler into the doc pages?

**Comment by sebastianbenz** [comment]
Hah - 1) has one problem I forgot about. We don't know the height in advance. In the case of the component sampler we could work around it by defining a default height and making it scrollable, but this is not an option for the source/preview example embeds. 

> > Each sample tab has additional documentation. How do we want to integrate it?

> At least for samples that are currently coming from abe.com we could maybe use the first doc section and add a link like "See full example"?

Have we got any mocks for how to include the docs? The component sampler won't work for all component samples, but for the ones where it works we will have only one doc section per sample.

**Comment by sebastianbenz** [comment]
+1 to shortcode

**Comment by sebastianbenz** [comment]
What do you think about the playground idea?

**Comment by matthiasrohmer** [comment]
> Hah - 1) has one problem I forgot about. We don't know the height in advance.

Oh I thought that was what you meant with *We'd need a good placeholder though* 😄

> Have we got any mocks for how to include the docs? The component sampler won't work for all component samples, but for the ones where it works we will have only one doc section per sample.

You are right, didn't thought that through. No mocks also - the one shown in the initial issue is the most accurate one.

>What do you think about the playground idea?

I would really like having a playground-powered embed-widget! Correct me if I am wrong: wouldn't this mean having nested iframes? So one providing the tabs and their functionality and then one holding the actual sample? Or would the tabs then be provided by amp.dev?

**Comment by matthiasrohmer** [comment]
This has been solved in parts: we link all examples using a specific component in the new component intro table.

Additionally we implemented the new `[example]` shortcode which enables documentation authors to add interactive examples directly into a document.
