### ISSUE TITLE
No options available for AMP email - Boilerplate Generator

### ISSUE THREAD

**Issue by brendanheyu** [ampproject/amp.dev#1732]
Hi folks,
On selecting the AMP email option on the Boilerplate Generator, there are no options shown.
Would love to see what I can build!

Thanks
Brendan

**Comment by sebastianbenz** [comment]
I've transferred the issue over to amp.dev which is going to replace ampbyexample. 

Thanks for the suggestion Brendan. Which options would you've liked to see there?

//cc @fstanis for more ideas

**Comment by brendanheyu** [comment]
Howdy!

I suppose I would like to see some parity in the centre dropdown showing valid examples of the subset of AMP components that are allowed to be used in AMP emails. As a UI guy that has been thrown into the email marketing game - AMP4email is pretty exciting right now. Most of the documentation available promises all the sweets in the candyshop - when you go to build a AMP4email, you're left with just the stale mints on the garage counter.
I'm hoping this might soften the blow :)

**Comment by brendanheyu** [comment]
I just went and visited amp.dev - BRILLIANT!

**Comment by sebastianbenz** [comment]
Thanks for the feedback Brendan! The boilerplate generator only includes non-trivial patterns, which there aren't for amp email (I'm probably wrong). But you're right, adding a few more common patterns would definitely help. 

@fstanis do you have bandwidth to document a few common patterns for amp mail (I'm thinking amp-list, form, ...)?

**Comment by brendanheyu** [comment]
form, list, select, carousel(?) - I'm just thinking about the hoardes of email developers that are going to rush to any font-of-knowledge with any amount info/examples/use cases

Thanks for listening!

**Comment by fstanis** [comment]
Most component samples (e.g. [amp-list](https://amp.dev/documentation/examples/components/amp-list/?format=websites)) work in emails with the following changes:

1.  Replace `<html ⚡4email>` with `<html ⚡>`
2.  Replace boilerplate with `<style amp4email-boilerplate>body{visibility:hidden}</style>`
3.  Remove `<link rel="canonical">` and `<meta name="viewport">` since these are not needed / supported in AMP for Email
4.  Make sure all URLs are absolute
5. Remove unsupported tags / CSS - for example, in case of `amp-list`, this is the animations and `reset-on-refresh` attribute

Since 1-4 seems easy to automate using a script, I was hoping we can do this "behind the scenes" if the URL contains `?format=email` (i.e. "email" is selected in the dropdown on amp.dev). Step 5 requires some more thinking, but I can see a few ways it can be done. My plan is to focus on that post-AMP Conf.

Hope this makes sense. If you have any ideas for email-specific samples that we could build (things we can't just copy from "regular" AMP), I'd love to hear that too.

**Comment by sebastianbenz** [comment]
@fstanis this is not about component sample, but about templates in the boilerplate generator.

**Comment by fstanis** [comment]
I was referring mainly to this part of @brendanheyu's comment:

> I suppose I would like to see some parity in the centre dropdown showing valid examples of the subset of AMP components that are allowed to be used in AMP emails.

Like you already mentioned, I don't see any email-specific patterns that could be added to the boilerplate generator and I don't think any of the component samples belong there (as opposed to the playground).

**Comment by matthiasrohmer** [comment]
As stated by Filip there are currently no specific options available for AMP4Email. Though in the meantime the example transformer has made a lot more examples for AMP4Email available for the playground.
