### ISSUE TITLE
Migration issue with amp-next-page component examples

### ISSUE THREAD

**Issue by noodles** [ampproject/amp.dev#1888]
The "[View Demo](https://amp.dev/documentation/examples/components/amp-next-page/preview/?format=websites)" and "[Open in Playground](https://playground.amp.dev/?url=https://preview.amp.dev/documentation/examples/components/amp-next-page)" examples linked to on the [amp-next-page component page](https://preview.amp.dev/documentation/examples/components/amp-next-page) are not functioning.

The console shows an error:
`"pages must be from the same origin as the current document"
`

The article links in the example code are still on the "https://ampbyexample.com" domain.
Substituting the ampbyexample.com URLs with the amp.dev equivalents still produces the same error.

e.g.

```
"ampUrl" : "https://ampbyexample.com/components/amp-img/"
-> "ampUrl" : "https://amp.dev/documentation/examples/components/amp-img/"
```

The AMP Playground URL points to preview.amp.dev

- Page link: https://amp.dev/documentation/examples/components/amp-next-page/

Browser: Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
O/S: MacOS 10.14.3

**Comment by ags1773** [comment]
I don't think this issue is fixed 

https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-next-page&format=websites&_gl=1*nmbayp*_ga*YW1wLWlmbndKanBIUVpMbGxINFViQXdmbEE.
![image](https://user-images.githubusercontent.com/27222520/82832738-9bf77880-9ed9-11ea-80db-dcd290d73b6a.png)
