### ISSUE TITLE
Support page is stale

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#2339]
The [SUPPORT.md](https://github.com/ampproject/amphtml/commits/master/SUPPORT.md) from ampproject/amphtml gets imported into amp.dev and is then publicly available on https://amp.dev/support/

Through [recent changes](https://github.com/ampproject/amphtml/commit/d24a5d48d9380c0f59f4fd6224b8395bdac32322#diff-b6de2700983073cf649bb620766ffce7) the page is now almost empty and not very helpful anymore. How do we want to proceed with it? Remove it from the top-level navigation? Do not import it but actually maintain it in this repository with useful content?

**Comment by matthiasrohmer** [comment]
@pbakaus, only assigned you for triage - let me know if I can help. Thanks!

**Comment by pbakaus** [comment]
Ugh this is a sad side effect that maybe @mrjoro didn't have on the radar (that this file is pulled in for amp.dev). Joey, thoughts?

We can of course just create our own support page in the docs repo.

**Comment by mrjoro** [comment]
Oof, sorry about that!  Yes, I didn't realize it was pulled into amp.dev.  We had so many different places in our repo pointing people where to get help that I thought it was getting harder to use (and easier to get in an outdated state).

Sadly the README.md also points people to the amp.dev support page. :)

Is it possible to pull in a subset of the README.md?  We could pull in the "Having a problem using AMP?" and the "Want to help make AMP better?" sections.

Otherwise a separate support page in the docs repo that just points to Stack Overflow and then different sections of this README could work.

**Comment by matthiasrohmer** [comment]
Increased priority as per #2443 and @cramforce.

**Comment by DerekNonGeneric** [comment]
I don't see why this issue is still open. Everyone's concerns seem to have been addressed. All of the content removed from the [old location](https://github.com/ampproject/amphtml/commit/d24a5d48d9380c0f59f4fd6224b8395bdac32322#diff-b6de2700983073cf649bb620766ffce7) is now present in the [new location](https://raw.githubusercontent.com/ampproject/amp.dev/0a03a0969acac2e8eb0b33f61e0457d730cde440/pages/content/amp-dev/support/index.md) and it is being pulled in properly.

**Comment by sebastianbenz** [comment]
@DerekNonGeneric you're right, we should fix the template!

**Comment by sebastianbenz** [comment]
Closing as fixed, open https://github.com/ampproject/amp.dev/issues/3282 to track updating the support page.
