### ISSUE TITLE
Change component docs title to documentation

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2491]
The current title is "Component: amp-sidebar", which is confusing:

<img width="712" alt="Screen Shot 2019-07-15 at 11 58 26" src="https://user-images.githubusercontent.com/380472/61208563-fccdf600-a6f7-11e9-9305-fcd78c84b944.png">

How about changing s/Component/Documentation. This would make it clear what the page is about and also is a more clear differentiation to the example page. 

@pbakaus @CrystalOnScript WDYT?

**Comment by matthiasrohmer** [comment]
Where is "Amp-sidebar" on the bottom left coming from, though? 🤔

**Comment by sebastianbenz** [comment]
That's the sample page. The title is actually `Example: amp-sidebar`, but it looks like the index hasn't picked it up yet.

**Comment by pbakaus** [comment]
+1. Sounds very reasonable to me I'm actually wondering if we should make it look more like a tag, like so:

```
<amp-sidebar> - Reference documentation – amp.dev
```

**Comment by sebastianbenz** [comment]
I like the tags. I'd put the doc type first though. The type might be truncated otherwise, as you can see in the screenshot.

**Comment by pbakaus** [comment]
Both orders work for me, but I found seeing the actual component when truncated slightly more important than the type of doc. But I'm not willing to die on this hill :)

**Comment by matthiasrohmer** [comment]
@sebastianbenz, can you confirm "Documentation: <amp-sidebar> - amp.dev" is what the title should be? 🙂Then one of us can take care of this.

**Comment by sebastianbenz** [comment]
Yes, let's go with:

`Documentation: <amp-sidebar> - amp.dev`
`Example: <amp-sidebar> - amp.dev`
`Demo: <amp-sidebar> - amp.dev`.  <-- instead of `Example preview`

I also liked Paul's suggestion of using `<>`.

**Comment by dlemm** [comment]
I’ve started updating the title tags and discovered, that updating the title to use < title > has some more implications. The components bar would look like in Screenshot 1. 
<img width="439" alt="component-sidebar" src="https://user-images.githubusercontent.com/28383171/61641717-eac3f880-ac9f-11e9-819a-d11583610279.png">

In addition to that, the files in the example/source folder have to be renamed to ```examples/source/1.components/%3Camp-3d-gltf%3E.html``` for example, in order to get the result in screenshot 2. 

<img width="698" alt="example" src="https://user-images.githubusercontent.com/28383171/61641752-fadbd800-ac9f-11e9-8080-5a9888a601fc.png">

 @sebastianbenz do you might have another solution for that or are you fine with this?

**Comment by sebastianbenz** [comment]
@dlemm doesn't this belong into a template (probably at the same place where you put `Documentation: `?

**Comment by matthiasrohmer** [comment]
@sebastianbenz, the template actually really just takes care of defining a prefix: https://github.com/ampproject/amp.dev/blob/86218d362f7108f05457ce022d182fb9ec4c5863/frontend/templates/views/partials/structured-data.j2#L47-L59

**Comment by sebastianbenz** [comment]
Can we set the whole title there?
