### ISSUE TITLE
Sidebar: broken markup

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2506]
```
<amp-sidebar id="sidebar-left"↩
  class="ap--ampsidebar"↩
  layout="nodisplay"↩
  side="left">↩
  <nav toolbar="(min-width: 768px)"↩
    toolbar-target="ap--sidebar-content">↩
    <ul>↩
```

the `ul` element doesn't really make sense here.

**Comment by sebil** [comment]
Hey Sebastian,
this seems like a bug, but it was intended, because of three reasons:

1. In order to make the `format-toggle` sticky I had to take it outside of the `sidebar-section`.
  Because the `sidebar-section` needs the _original height_ of the sidebar with all it's elements, the `format-toggle` couldn't be sticky as a child element of it. They had to be on the same level.

2. When I brought the `format-toggle` and `sidebar-section` on the same level, I got this amp validation error:
**`Tag 'amp-sidebar > nav' must have 1 child tags - saw 2 child tags.`**

3. Which first leaded me to wrap them (of course in a div), but than I got this amp validation error:
**`Tag 'div' is disallowed as child of tag 'amp-sidebar > nav'. Child tag must be one of ['ol', 'ul'].`**

So it ended up using a `ul`...

I know, semantically this isn't the best solution, but to make it 100% amp conform, we could only put `<li>` in an amp-sidebar and nothing else.
