### ISSUE TITLE
Use amp-carousel 0.2 in amp.dev

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#2766]
Now that we have released amp-carousel 0.2 should be available on August 28 we should upgrade the following to use the new carousel:
- The amp-carousel demos
- The implementation of amp.dev using any carousels.  

For more details please see documentation here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/amp-carousel.md

**Comment by matthiasrohmer** [comment]
Wohoo 🎉

**Comment by tharders** [comment]
Currently amp-carousel is no longer listed in the generated dist/static/files/component-versions.json.
It seems something in the https://cdn.ampproject.org/v0/validator.json has changed so that is no longer found as extension.
The component examples do not specify a version, so they will use the default version 0.1 since no latest version is available in the above file. @sebastianbenz can you have a look at this?

It would be good if the component docs would specify the version explicitly, so that the 0.1 examples would use 0.1 and the new documentation would use 0.2.
Although this would not work for components that are used generally on the amp.dev (like amp-sidebar, amp-bind, amp-list, amp-mustache). Using different versions currently results in an error.

Also we noticed that the new amp-carousel does not have a sliding animation as it is the case with 0.1 which really looked much nicer. Maybe we can add this manually for the carousels we use explicitly on amp.dev, but not for the examples. @sebastianbenz What do you think?

**Comment by tharders** [comment]
Just found out that the sliding problem is only in safari. In chrome the sliding is still nice also with 0.2.

**Comment by tharders** [comment]
We found some problems with amp-carousel 0.2 and should wait a little bit until fixes for those problems are available in prod.
https://github.com/ampproject/amphtml/issues/24627
https://github.com/ampproject/amphtml/issues/24632
https://github.com/ampproject/amphtml/issues/24628

**Comment by matthiasrohmer** [comment]
Done in the meantime.
