### ISSUE TITLE
Table of contents in courses now appears twice

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#2774]
See, for example, [https://amp.dev/documentation/courses/beginning-course/our-first-amp-page/](https://amp.dev/documentation/courses/beginning-course/our-first-amp-page/).

The entries in the table of contents appear twice.

/cc @dlemm @matthiasrohmer 

Otherwise the new toggle looks really nice! :)

**Comment by matthiasrohmer** [comment]
😕 Thanks for the report, Ben! Sadly I can't think of a good technical solution for this. One thing that would fix it partly though is to only duplicate sections that actually differ in content. This would also make maintenance a lot easier. Currently even course documents that are equal for beginners and experts have the same content wrapped by `[filter]` tags.

But even with this section headlines that are hidden by `[filter]` still show up as Grow has no clue of those tags and simply gathers all headlines from the document... I'll need to think about it a little more.

**Comment by morsssss** [comment]
Welllll.... I remember that when we first looked at these courses on the site, I asked if we could simply hide the table of contents. It's somewhat useful, but no single webpage is that long... and the real downside is that the remaining width for code samples is small, so you have to scroll around to read the code samples.

In other worse, I think the usefulness of the table of the contents is outweighed by the fact that it makes the code samples hard to read.

Can we just suppress the TOC for now? Or permanently? 😃

**Comment by tharders** [comment]
@dlemm  will disable the table of contents for the courses to have a quick fix this problem.
But we must prevent the underlying problem, since also the format filters are affected.

For example the paragraph "Disallowed property inside attribute in tag" on following page:
ttps://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors/?format=websites#disallowed-property-inside-attribute-in-tag
is not available for email:
https://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors/?format=email#disallowed-property-inside-attribute-in-tag

It feels like the most clean solution to fix the table of contents with filtering would be to add filter commands directly when the table of contents html code is generated.
We already patched the markdown TocTreeprocessor, so it would be possible to take this a step further.
