### ISSUE TITLE
Document how to retrieve the width and height in common platforms

### ISSUE THREAD

**Issue by cramforce** [ampproject/amp.dev#279]
We should have some sample code how people can retrieve the width and the height of an image resource in common platforms such as

- wordpress
- raw PHP
- node.js

https://twitter.com/rem/status/811673647819722752

**Comment by bpaduch** [comment]
@amedina or @pbakaus - Any chance you can create this sample code? If you create it, I can document it.
cc: @sebastianbenz - maybe this can be tied into ABE, not sure?

**Comment by mjangda** [comment]
If you're using the "AMP for WordPress" plugin, it handles things for you automatically when rendering the content: https://github.com/Automattic/amp-wp/blob/master/includes/utils/class-amp-image-dimension-extractor.php (this was one of the more painful aspects of building the WordPress plugin -- people love hotlinking images :))

Under the hood, the plugin uses the `fasterimage` library (https://github.com/willwashburn/fasterimage) and for backwards compatibility (PHP5.2/PHP5.3), the plugin uses its predecessor `fastimage` (https://github.com/tommoor/fastimage).

Fasterimage is nice since it uses streaming and in many cases only needs to do a partial download to get the size. It also supports batch processing of images as well.

Both these libraries can be used in any PHP project.

**Comment by bpaduch** [comment]
@cramforce - Based on the comment above where WordPress does it automatically, and the code can be used in PHP.  Do you still see a need to keep this issue open?

**Comment by cramforce** [comment]
I think this would be great to do.

**Comment by sebastianbenz** [comment]
Closing this in favor of https://github.com/ampproject/amp-toolbox/issues/499
