### ISSUE TITLE
Fix pages with missing component imports

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2914]
See https://docs.google.com/spreadsheets/d/1yYwlpCrRra2MTLYnoc8bhFY9PdXtxG_xQj0QnDPDu7A/edit#gid=0

**Comment by matthiasrohmer** [comment]
All URLs pointing to the `amp-lightbox` documentation should be fixed by #2922 as well. They all had `<code><amp-lightbox></code>` in them.

The `/examples/**` URLs seem to be fine now by checking a few of them. I'd like to recheck in a few days.

`amp-facebook` docs need to be fixed upstream in ampproject/amphtml.

**Comment by matthiasrohmer** [comment]
Created amphtml/#24426 to fix `amp-facebook`.
