### ISSUE TITLE
local builds of amp.dev should reflect local changes to ampproject/amphtml repo

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#2965]
## Feature Request

When editing component files in amphtml, it would be helpful to see the changes reflected in local builds of amp.dev without having to copy/paste code back and forth.

**Comment by matthiasrohmer** [comment]
@sebastianbenz, I remember the old importing functionality allowed to specify a path to a local clone of ampproject/amphtml. That functionality got lost for a reason I can't get together anymore.

But still it would require to run the full import against the local clone if one doesn't implement a file watching method or similar.

**Comment by CrystalOnScript** [comment]
Calling @pbakaus for further information on this one

**Comment by pbakaus** [comment]
hey folks, @matthiasrohmer is correct, the way to go for now is to support running the importer against a local clone, instead of the remote Github API.

I already put some scaffolding in place for this in my latest versioning etc. extensions, but the missing link is that the directory listings still come from the Github API, so whoever takes on this work needs to abstract where we list directories in the importer into a function or class that either uses the Github API or a local file path.

A bonus nicety would be to add query params to `importComponents` so you can import the component you're working on only.
