### ISSUE TITLE
Don't optimized shared fragments

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2970]
See https://github.com/ampproject/amp.dev/pull/2934#issuecomment-531443543

**Comment by matthiasrohmer** [comment]
My bad, missed this when implementing https://github.com/ampproject/amp.dev/pull/2548. I see two ways to go about this:

1) Add a blacklist to the pages router containing all paths that should not be optimized
2) Implement a dedicated router for the shared pages instead of serving them through growPages.js

Anyway I am wondering why they get optimized on request in the first place. Doesn't the optimizer skip DOM fragments and only processes complete documents?

**Comment by sebastianbenz** [comment]
I'm fine with both approaches. Optimizer transformers also work on fragments to support optimizing template partials.
