### ISSUE TITLE
Markdown parser not working as expected

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp.dev#3048]
In some cases the markdown parser does not seem to be extracting/converting the markdown embedded within HTML comments to HTML.

For example https://amp.dev/documentation/examples/components/amp-video/#hls-support has raw markdown embedded:

![Screenshot from 2019-10-01 11-20-19](https://user-images.githubusercontent.com/51244/65954304-a42c1080-e43d-11e9-808f-78d61512d114.png)

Expected: the text "shaka packager" is a link to <https://github.com/google/shaka-packager>.

**Comment by sebastianbenz** [comment]
//cc @tharders @matthiasrohmer

**Comment by tharders** [comment]
@sebastianbenz:
The example parser converts the whitespace at the start of the line into an extra newline character.
So we have two newlines for each line in the description comment which results in paragraphs for each line instead of one paragraph for the whole text. Links that go over multiple lines are then split between two paragraphs and no longer recognized as links.

Maybe we could change the indention inside the comment blocks automatically.
But this is a little tricky since some indention is required.
I think it would be best if we can fix this in the amp by example parser.

**Comment by sebastianbenz** [comment]
The ABE parser normalizes whitespace already. However, samplesBuilder.js circumvents this by accessing the private `doc_` field [here](https://github.com/ampproject/amp.dev/blob/future/platform/lib/build/samplesBuilder.js#L276) instead of using `parsedSample.doc` which will return the normalized version.
