### ISSUE TITLE
Roadshows page now has "Jump to:" area on top

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#3149]
### Current Behavior
At the [roadshows page](https://amp.dev/events/amp-roadshow/), on my MacBook, I currently see a big area that's blank save for the words "Jump to:". Screenshot:

<img width="1053" alt="Screen Shot 2019-10-27 at 2 17 41 PM" src="https://user-images.githubusercontent.com/29419498/67639317-b37b6e00-f8c4-11e9-9e7f-9fb8ab00cf4e.png">

**Comment by sebil** [comment]
This was caused because of the latest grid-layout fixes for chrome canary, see #3110 for details.

The `jump-to` organism wasn't fitting into the grid anyway and also I recognized, that it was duplicated code in 4 different files with minimal differences.

I decided to completely refactor the whole thing, so we can reuse it again. For the minimal differences, I used variables that could be passed with the inclusion of the template partial.
