### ISSUE TITLE
Better navigation tools for the blog

### ISSUE THREAD

**Issue by tobie** [ampproject/amp.dev#3152]
## Feature Request

# Is your feature request related to a problem? Please describe.

It's super hard to find past content on the blog.

# Describe the solution you'd like

* Search tool
* category index in the sidebar
* category index pages with only the blog title and date plus eventually a short extract, **not** the whole blog post!
* archive index pages by month and year (again with just the title and categories, not the whole article as is currently the case).

# Describe alternatives you've considered

`site:blog.amp.dev` on search.

**Comment by matthiasrohmer** [comment]
Hi @westonruter & @amedina could you and/or your team have a look at this? 🙂Let us know if we can help in any way.

**Comment by westonruter** [comment]
For context here see https://github.com/ampproject/amp.dev/pull/2934#issuecomment-531443543. This is why the search markup is currently disabled on the blog.

It is blocked by https://github.com/ampproject/amphtml/issues/24661 which would be fixed by this PR: https://github.com/ampproject/amphtml/pull/24793

**Comment by westonruter** [comment]
I'm finally getting to this.

@mathiasbynens I found a blocker, however. The search endpoint is returning relative URL results. For example https://amp.dev/search/highlights is returning URLs like `/documentation/guides-and-tutorials/start/converting/`. The same goes for the https://amp.dev/search/do

Can these endpoints be updated to return the URL with the host name? Otherwise they result in 404s. The alternative would be to hack the Mustache template to inject `https://amp.dev` before the template variables.

**Comment by westonruter** [comment]
Another complication: The [shared header AMP fragment](https://amp.dev/shared/header/) includes the use of transformed AMP attributes and class names. These are causing validation errors in the AMP plugin which are causing its sanitizer remove them. This is problematic for class names since currently the plugin removes the _entire_ class name when it contains `i-amphtml-*`. Can this fragment be made non-optimized?

**Comment by westonruter** [comment]
I can work around this by doing:

```php
$header = preg_replace(
	'/\bi-amphtml-([a-z-]+)(=".*?")?/s',
	'',
	$header
);
```

I can't, however, safely work around the issue with the relative URLs being returned in the search result endpoints.

**Comment by sebastianbenz** [comment]
@matthiasrohmer can you please take a look

**Comment by matthiasrohmer** [comment]
Will do. Can't get my head around how whenever we touched the optimizing process the shared fragments ended up optimized 😅

**Comment by matthiasrohmer** [comment]
Okay, actually everything seems fine this time. When requesting `curl https://amp.dev/shared/header/` you'll get the unoptimized fragment. When testing with Chrome it's optimized as you'll receive the SXG.

Absolute URLs for search results are coming with #3304.

**Comment by westonruter** [comment]
> Okay, actually everything seems fine this time. When requesting `curl https://amp.dev/shared/header/` you'll get the unoptimized fragment. When testing with Chrome it's optimized as you'll receive the SXG.

Really? 

```
$ curl https://amp.dev/shared/header/ | ack '\bi-amphtml-[a-z-]+(=".+?")?' -o | sort | uniq -c | sort -nr | head -n 10
  11 i-amphtml-screen-reader
  11 i-amphtml-element
   8 i-amphtml-wrapper
   8 i-amphtml-layout-container
   6 i-amphtml-layout-size-defined
   4 i-amphtml-notbuilt
   4 i-amphtml-loading-container
   4 i-amphtml-layout="container"
   4 i-amphtml-fie
   3 i-amphtml-singledoc
```

Does not the presence of these `i-amphtml-*` class names and attributes indicate optimized AMP?

**Comment by westonruter** [comment]
Also: 

```
$ curl https://amp.dev/shared/header/ | ack '<html[^>]+>' -o
<html i-amphtml-layout="" i-amphtml-no-boilerplate="" transformed="self;v=1">
```

It's explicitly marked as optimized via `transformed` when I `curl` it.

**Comment by matthiasrohmer** [comment]
You're absolutely right, sorry. I only quickly checked locally if [growSharedPages.js](https://github.com/ampproject/amp.dev/blob/future/platform/lib/routers/growSharedPages.js) is called correctly and then drew assumptions about the rest. This router should actually send the fragments while bypassing any optimization. As this was my one quick idea I need to do a more detailed investigation...

Somewhat the same for #3304: I thought that all URLs are going through `createPageObject` and missed the rest. I have a fix ready for the remaining relative ones in `/search/do` but am still missing some for `/search/highlights` - at least I think so from looking at the tests. I opened #3317 and triaged to @tharders who wrote the search initially.

**Comment by westonruter** [comment]
I've pushed up the current WIP onto this multidev environment: https://search-nav-amphtml-blog.pantheonsite.io/2019/12/20/ccpa-support-in-amp/

In addition to the URLs in the REST API endpoint needing to be made absolute, I'm also seeing something strange where doing a search results in the `amp-list` appearing broken and I'm not immediately sure why:

![image](https://user-images.githubusercontent.com/134745/71302805-957e3700-2364-11ea-86a7-3c8cce3c6b56.png)

Additionally, since the blog is not translated I'm currently adding this CSS:

```css
.mainmenuopen .ap-m-language-selector,
.ap-m-language-selector {
	display: none;
}
```

This works fine, but when I click on the 🔍 search button on mobile, it gets moved over to the far left unexpectedly:

![image](https://user-images.githubusercontent.com/134745/71302826-e4c46780-2364-11ea-817f-cdb49c981f58.png)

I'd appreciate help debugging these two issues.

**Comment by westonruter** [comment]
Happy new year! Please let me know when you'd anticipate continuing to work on this.

**Comment by matthiasrohmer** [comment]
Apologies for the delay, @westonruter!

https://amp-dev-staging.appspot.com/search/highlights and https://amp-dev-staging.appspot.com/search/do?q=amp-accordion now both return absolute URLs as per #3317. 

For the other issues you were mentioning in the comment above I created #3498, #3499 and #3500. I'll notify you once they're all in and deployed so you can continue your work 🙂

**Comment by westonruter** [comment]
@matthiasrohmer It appears that the fragments are getting optimized again:

![image](https://user-images.githubusercontent.com/134745/85895934-6bdb1800-b7ac-11ea-956a-90cafbe540ff.png)

**Comment by patrickkettner** [comment]
@westonruter are the blockers for this up to date on this thread?

**Comment by westonruter** [comment]
@patrickkettner yes. One is the previous comment, where the fragments are getting optimized. No optimization should be done since it will be done by WP, and WP expects non-transformed markup.

**Comment by patrickkettner** [comment]
@westonruter how are the fragments imported? Via url? If it is of any value, you can toggle optimization for any URL with a `?optimize=false` flag appended to it. (e.g. https://amp.dev/shared/header/?optimize=false). If it is a processed version of the document itself, I can update the build to be in a non transformed format.

**Comment by westonruter** [comment]
Excellent. That is very helpful. I've updated the logic to import the unoptimized file, discontinued removal of the search elements, and then I've updated the SCSS to import `organisms/search.scss` and `molecules/search-trigger.scss`. See the result here: https://test-amphtml-blog.pantheonsite.io/

If good, I'll deploy live.

**Comment by patrickkettner** [comment]
looks good to me! @tobie @sebastianbenz y'all good with it?

**Comment by sebastianbenz** [comment]
LGTM

>

**Comment by westonruter** [comment]
Deployed. https://blog.amp.dev/?cache-busted
