### ISSUE TITLE
Content from WordPress uses incorrect image format

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amp.dev#3245]
### Current Behavior
Blog posts featured on the homepage use `png` format for embedded images, increasing their size significantly compared to the `webp`/`jpg` fallback format used on other items across the homepage.

Please also provide:
- Page link: https://amp.dev/
![Screen Shot 2019-11-27 at 10 07 04 AM](https://user-images.githubusercontent.com/61764/69748658-b5239600-10fd-11ea-8c72-d8656db443e9.png)

### Expected behavior/code
For photographs, use a lossy image format instead of a lossless or vector format.

### How do we reproduce the issue?
1. Visit `amp.dev`.
2. Inspect the image format used for Blog posts.

What browser are you using? Chrome 78
What O/S are you using? Mac OS

**Comment by sebastianbenz** [comment]
//cc @westonruter whether this is supported by WP

**Comment by westonruter** [comment]
WordPress does not currently support WebP directly, although there are issues (e.g. [24718](https://core.trac.wordpress.org/ticket/24718), [35725](https://core.trac.wordpress.org/ticket/35725)) which have discussed it for future.

The PNG being used for that blog post ([People Behind The Code](https://blog.amp.dev/2019/11/15/people-behind-the-code-ndtvs-rise-to-global-heavyweight/)) is present because it is the format uploaded to WordPress in the first place. The quick win here is to transcode it to JPEG and re-upload.

Otherwise, if WordPress were to directly support WebP then it would have to transcode every image uploaded, increasing server resources (CPU processing and storage requirements). For browsers that don't support WebP it would need to serve two image formats.

**Comment by westonruter** [comment]
So the quick fix is an editorial one: ensure that those creating content for the AMP blog use the right format.

If WebP is desired on amp.dev, the transcoding would most easily be done as part of amp.dev when consuming the REST API from WordPress.

**Comment by matthiasrohmer** [comment]
The posts that are currently showing don't have images or meet the editorial requirements outlined by Weston.

Additionally, #3486 updated the behaviour to use the designated post thumbnails over the original images which also increased performance.

Therefore closing this.
