### ISSUE TITLE
🐛 Success Stories category labels always show 'websites'

### ISSUE THREAD

**Issue by noodles** [ampproject/amp.dev#3387]
### Current behavior

On the Success Stories page, with the 'All' button selected, all of the story summaries are labelled as 'websites'.

![Screen Shot 2020-01-17 at 10 51 59 AM](https://user-images.githubusercontent.com/183972/72572700-7f3da980-3917-11ea-930a-9552b762acf4.png)

The behaviour persists when you click on any of the category filter buttons.

Clicking on 'advertisers' -> 'websites'

![Screen Shot 2020-01-17 at 10 45 12 AM](https://user-images.githubusercontent.com/183972/72572393-7a2c2a80-3916-11ea-9e0f-45729ee49762.png)

Clicking on 'publishers' -> 'websites'

![Screen Shot 2020-01-17 at 10 48 02 AM](https://user-images.githubusercontent.com/183972/72572505-e313a280-3916-11ea-8d00-ca41f8be295f.png)

- Page link: https://amp.dev/success-stories/

### Expected behavior/code

The category label on the story summary should match the category button that the user clicked on.

### Reproduction procedure
Please provide the steps to reproduce the problem:

See above

- What browser are you using?
Chrome Version 79.0.3945.117 (Official Build) (64-bit)
Safari Version 13.0.4 (15608.4.9.1.3)
- What O/S are you using? MacOS Catalina 10.15.2

**Comment by matthiasrohmer** [comment]
Thanks for your feedback, @noodles! The UI here is indeed not really consistent: actually the category buttons have no connection to the format indicators and are two different things.

I quickly discussed this with our designer: the format indicator does not make too much sense for a success story as the product the story is about may be built using multiple AMP formats. The BMW.com for example makes use of AMP as well as AMP Stories.

Therefore we would revise the labels to contain the category (which is not shown anywhere on the teaser currently, hence the confusion I guess) instead of the format. This should provide the user with a clearer idea of what's happening when you filter.

@sebastianbenz, you've got any opinion on this?

**Comment by sebastianbenz** [comment]
SGTM - thanks for looking into this Matthias
