### ISSUE TITLE
Simplified Chinese ( zh-CN ) translation of the amp.dev website

### ISSUE THREAD

**Issue by andyc15** [ampproject/amp.dev#3496]
### Simplified Chinese ( zh-CN ) translation
Wish to update pages/translations/zh_CN/LC_MESSAGES/messages.po
I've already translated Partial File ( almost done )
More translation details will need specific explanation.
May need another one or two hours to complete the translation
Also @CrystalOnScript

**Comment by andyc15** [comment]
**TRANSLATION ALMOST COMPLETED!**
Updates:

- Microadjust some translation
- I didn't translate titles like "The Best Battle Royale on PC" and publishers like "USA Today". Notice me if those also need to translate.
- Also does "playground" need to be translated to something like "online editor" or "experiment zone"?

**Comment by patrickkettner** [comment]
Hey @andyc15 
there was actually a fairly significant change to the PO file (its much larger now), so you will need to rebase. If you post your current progress Id be more than happy to merge the changes since you are already being so generous with your time. 

As to your questions...

> I didn't translate titles like "The Best Battle Royale on PC" and publishers like "USA Today". Notice me if those also need to translate.

proper nouns like company names, and things that are from external sources (like the names of websites, like "The Best Battle Royale on PC" or "Olga and the kings") should not be localized, so they are safe to ignore

> Also does "playground" need to be translated to something like "online editor" or "experiment zone"?

between those two, "experiment zone" is closer to the intention.

Please feel free to let me know if any other questions are needed, and thank you _very_ much for the work

**Comment by andyc15** [comment]
Hi
Much larger file needs Much more time to translate now.
**The current process: 1/2**
Some misspelling was found like "Affiliate link → Affliate link".
Pull request created.

**Comment by patrickkettner** [comment]
completed in #3606
