### ISSUE TITLE
Component table bugs

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3540]
Looks like a few review comments (code and design) have not been addressed:

* import script and tag backgrounds are still different
* description is shown twice here: https://amp-dev-staging.appspot.com/documentation/components/amp-animation/?format=websites
* import script padding still not consistent, suggestion: `4px 6px;`
* this page should have samples: https://amp-dev-staging.appspot.com/documentation/components/amp-brightcove/?format=websites (they're missing for others as well, e.g. https://amp-dev-staging.appspot.com/documentation/components/amp-animation/?format=websites)
* copy button doesn't work: 

  ```
    copy-script:34 Uncaught ReferenceError: $scriptTag is not defined
        at HTMLDocument.<anonymous> (copy-script:34)
    (anonymous) @ copy-script:34
  ```
* mobile version looks still weird with so many layers 

<img width="326" alt="Screen Shot 2020-02-14 at 13 54 02" src="https://user-images.githubusercontent.com/380472/74533290-81545180-4f31-11ea-83e0-b0fe6b377489.png">

**Comment by matthiasrohmer** [comment]
> * import script and tag backgrounds are still different

Triaging to @LongoOfficial again as soon as he's back in the office. Briefly chatted with him about it this week: the code snippet background grey is the same as for all other inline code snippets on the page to stay consistent after we've changed it from the black used for the code blocks. Using the same dark grey for the table background felt too heavy for Longo and using the light grey for the inline code snippet would break consistency.

> * description is shown twice here: https://amp-dev-staging.appspot.com/documentation/components/amp-animation/?format=websites

Is going to be fixed by https://github.com/ampproject/amphtml/pull/26383.

> * import script padding still not consistent, suggestion: `4px 6px;`

Similar to the background color discussion, the current padding is inherited to the inline code snippet plus added vertical padding for the scrollbar. But I agree `4px 6px;` looks more decent.

> * this page should have samples: https://amp-dev-staging.appspot.com/documentation/components/amp-brightcove/?format=websites (they're missing for others as well, e.g. https://amp-dev-staging.appspot.com/documentation/components/amp-animation/?format=websites)

Yep, I'm currently on this. This only happens on Travis due to the shared build.

> * copy button doesn't work:

@robinvanopstal: your call.

> * mobile version looks still weird with so many layers

Indeed, missed to create a follow-up issue as I did for #3528. If I remember correctly we decided to get rid of the nested boxes/layering all along including the tinted format-background. As this requires fairly substantial changes to the overall styling we wanted to isolate it from the tables. Is that still the case? 

What do you think in general? Shall we revert again or go with it for now? I am open for both, I mainly wanted to check how things go on Travis and didn't want to let the PR get any bigger.

**Comment by sebastianbenz** [comment]
We should fix the nits straightaway and then it's good to go for now.

**Comment by matthiasrohmer** [comment]
Followed up in #3547.
