### ISSUE TITLE
amp-layout.md is not appearing on amp.dev sidebar 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#3549]
[amp-layout](https://github.com/ampproject/amphtml/blob/master/builtins/amp-layout.md) is missing from amp.dev component sidebar 

It is [here](https://amp.dev/documentation/components/amp-layout/)
<img width="243" alt="Screen Shot 2020-02-14 at 1 23 38 PM" src="https://user-images.githubusercontent.com/23297417/74568702-6d0e5580-4f2d-11ea-881b-a6799906ab8f.png">

**Comment by matthiasrohmer** [comment]
Thanks! Never noticed this. The problem is that it isn't made available for any format. Fixed this with https://github.com/ampproject/amphtml/pull/26820.

The question is: does it make sense to force-enable `websites` for components that haven't have available formats defined in their frontmatter? Which shouldn't be the case after https://github.com/ampproject/amphtml/pull/26383 but ... @sebastianbenz?
