### ISSUE TITLE
amp-next-page reference documentation is invalid 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#3773]
### Current behavior
The errors from the validator make it seem like the page is using amp-next-page. It currently has no inline executable code samples. I am unsure what it is invalid. 

Please also provide:
- Page link: https://amp.dev/documentation/components/amp-next-page/?format=websites
- (Optional) Screenshots/videos:
<img width="1434" alt="Screen Shot 2020-03-26 at 3 21 53 PM" src="https://user-images.githubusercontent.com/23297417/77702479-da25f980-6f75-11ea-8601-2ab025ee02df.png">

**Comment by sebastianbenz** [comment]
@matthiasrohmer can you take a look? Is this related to the regex based auto import?

**Comment by matthiasrohmer** [comment]
Hm... we switched to explicit imports with https://github.com/ampproject/amp.dev/pull/2367 so I fear it's the AMP optimizer that is injecting `amp-next-page` here. 

I guess the reason is the literal `<amp-next-page>` in the *max-pages*  section of the [document](https://github.com/ampproject/amphtml/blob/master/extensions/amp-next-page/amp-next-page.md) which is interpreted as a tag. Will test this and eventually fix in ampproject/amphtml.

**Comment by matthiasrohmer** [comment]
Will be fixed by https://github.com/ampproject/amphtml/pull/27477
