### ISSUE TITLE
[blog] Fix quote formatting

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3919]
We should have a proper formatting for quotes:

<img width="951" alt="Screen Shot 2020-05-07 at 11 27 20" src="https://user-images.githubusercontent.com/380472/81290137-d3f06600-9067-11ea-9863-d83cb05429f2.png">

@matthiasrohmer @westonruter where's the best place to fix this?

**Comment by matthiasrohmer** [comment]
We have fancy quotes for the [success stories](https://amp.dev/success-stories/impremedia/):

![Uploading Bildschirmfoto 2020-05-07 um 13.46.34.png…]()

If they work I am happy to provide sample markup and the required CSS for anyone on the blog team to integrate.

**Comment by sebastianbenz** [comment]
This would be much better!

**Comment by sebastianbenz** [comment]
@westonruter can you help integrate this into the blog?

**Comment by westonruter** [comment]
Yes, but for the blog I don't think it makes sense to have the organization duplicated with the quote. The quote block in WordPress provides a text field for providing the quote attribution, but not for selecting some image to use for a secondary attribution.

Would this fancy quotation style be used for _every_ blockquote or just special ones?

**Comment by patrickkettner** [comment]
@sebastianbenz did you have an opinion on @westonruter's question?

**Comment by sebastianbenz** [comment]
I think the organization is not relevant in this case. I think we should use it for every quotation as long as we haven't got anything better.

**Comment by patrickkettner** [comment]
@westonruter is this something I can help with adding?

**Comment by westonruter** [comment]
@patrickkettner yes… what I am unclear on is the styling. 

For the [CWV post](https://blog.amp.dev/2020/05/06/amp-web-vitals-a-better-web-together/ ) specifically I can see an issue is that it has the Large style assigned rather than the Default:

![image](https://user-images.githubusercontent.com/134745/108801330-4fb19580-754a-11eb-8612-0a3e2d93fac3.png)

But when I select Default, the styling is worse:

> ![image](https://user-images.githubusercontent.com/134745/108801347-5a6c2a80-754a-11eb-86a5-ec3b67ca44ff.png)

So I've just put in a quick fix for that by adding this style rule:

```css
.wp-block-quote.is-style-default {
	padding-left: 2ex;
}
```

Now it looks much better (along with combining those two quote blocks):

> ![image](https://user-images.githubusercontent.com/134745/108801514-c9e21a00-754a-11eb-9b8f-08b3501cfa64.png)

This styling looks better to me than the success stories fancy quote.

In any case, you can just share the CSS you'd like to have up there. Or you can login to the Customizer in the site admin to add the desired CSS, and then I can add it to the repo as opposed to having it only be in the DB.

**Comment by patrickkettner** [comment]
thanks so much! the update looks great, I will talk with sebestian in the morning to see if we're all good

**Comment by sebastianbenz** [comment]
LGTM - thanks Weston!
