### ISSUE TITLE
Sync Analytics vendor list with the ampproject/amphtml repo

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amp.dev#3926]
### Problem
https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics-vendors/?format=websites#vendors
is outdated. 

### Solution
Can we sync the doc to the list in ampproject/amphtml repro. So one only need to add doc in one place.  

### Additional information (optional)
If I get it right, we are auto syncing the ad vendor list. Is it something that can be applied to analytics vendor list as well?

**Comment by sebastianbenz** [comment]
We definitely should do this. //cc @matthiasrohmer

**Comment by zhouyx** [comment]
the ampproject/amphtml repo doesn't have a full list that can export currently. Let me know what works best for you, and I can generate and maintain such a list on our side.

**Comment by matthiasrohmer** [comment]
The [Analytics Vendors](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics-vendors/?format=websites#vendors) page is currently rendered from this Markdown document: [/pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors.md](https://github.com/ampproject/amp.dev/blob/future/pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors.md). You're correct that this list is maintained manually but this also comes with a benefit: it is easily localizable and has already been translated to Spanish, Indonesian, Japanese, Portuguese and Chinese.

Of course we could adapt to how it's done with `amp-ad`: here we are importing the component doc with all other components and it directly contains the list of vendors. So adding all analytics vendors to [/extensions/amp-analytics/amp-analytics.md](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md) would solve this. This would also be my recommendation because this would get all the information in the same place - for both users and contributors and the workflow for translating component docs are already in place.

What's a little confusing: the ad vendors are currently listed twice on amp.dev - in the imported `amp-ad` doc (fresh and up-to-date) and manually maintained (and hence probably outdated) in the [FAQs](https://amp.dev/support/faq/platform-and-vendor-partners/) (data source: [/pages/shared/data/faq.yaml](https://github.com/ampproject/amp.dev/blob/future/pages/shared/data/faq.yaml)). I'd vote to remove the later one, if there aren't any objections.

**Comment by zhouyx** [comment]
Thank you for the detailed info. Just learnt that we are translating the manually maintained analytics vendor list, and that's awesome! 

I like the approach you recommended. As stated in the [integration guideline](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md), analytics vendors are asked to submit a separate Pull Request to the amp.dev repo today. 
If we can keep the global list in the ampproject/amphtml repo, the analytics working group can help enforce document update in code review. Also it's less work for analytics services to integrate. 


>What's a little confusing: the ad vendors are currently listed twice on amp.dev - in the imported amp-ad doc (fresh and up-to-date) and manually maintained (and hence probably outdated) in the FAQs (data source: /pages/shared/data/faq.yaml). I'd vote to remove the later one, if there aren't any objections.

I verified, the list in the FAQs is indeed outdated. And +1 to remove the later one. The two lists confused me even with the context above : P

What I can do is to move the analytics [list and content](https://github.com/ampproject/amp.dev/blob/future/pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors.md) from amp.dev repo to amphtml repo under a file `extensions/amp-analytics/analytics-vendors-lists.md`. The caveat is that we will lose the localization and translation that we already have. Any idea how we bring localization back?

**Comment by matthiasrohmer** [comment]
That sounds like a plan 🙂 As soon as the new `extensions/amp-analytics/analytics-vendors-lists.md` is in place (and on master) we can add it to the [importer configuration](https://github.com/ampproject/amp.dev/blob/future/platform/config/imports/spec.json).

Translation can then happen as with any other document just with the little downside that the translated documents will be maintained in this repository here rather than in ampproject/amphtml.

**Comment by zhouyx** [comment]
https://github.com/ampproject/amphtml/pull/28321

**Comment by zhouyx** [comment]
The doc has been merged to master and is ready to be imported. 
I'm not sure what to put for the `order` and `to` filed in the spec.json. @matthiasrohmer could you help add the file to the importer configuration? Here it is https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vendors-list.md

Thank you!

**Comment by zhouyx** [comment]
Friendly ping. @matthiasrohmer Let me know what's the next step. Thank you

**Comment by matthiasrohmer** [comment]
@zhouyx, sorry for the delay! I'll come back to this tomorrow 🙂
