### ISSUE TITLE
Table borders only shown for first column

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amp.dev#419]
Table borders look odd in https://www.ampproject.org/docs/reference/components/ads/amp-experiment
Looks like the border only applied to first child, which doesn't work well for tables with more than 2 columns
![table-borders](https://cloud.githubusercontent.com/assets/1012254/24519954/a0e581a0-1554-11e7-8026-da998b01e042.png)

Ideally, would like borders in between columns.

**Comment by techhtml** [comment]
What do you think about change HTML code `<td colspan="3"></td>` to `<th colspan="3"></th>` and add CSS code `th:only-of-type { border-right: 0 }`?

**Comment by pbakaus** [comment]
I didn't touch this yet (even though it's a simple fix) because I'm actually pretty sure it's supposed to look that way. I actually *like* the fact that the border visually highlights the first column, as the first column is the one that is the one that informs the rest (the name).

Of course, it wouldn't work with three columns that all have equal priority. I'm therefore all for introducing another style, but not sure about this specific instance.

**Comment by techhtml** [comment]
I also think that.

If Table has only one column, that column should do not have any borders. so I think it should add `only-child` CSS for only one column.

**Comment by bpaduch** [comment]
Further complicated when table uses `rowspan`.  In  the following example ([amp-bind](https://www.ampproject.org/docs/reference/components/amp-bind#element-specific-attributes)), it uses "rowspan=2", but there's only two `<td>` elements in the row, and you don't want border to show for that row's first-child:

![table-with-rowspan](https://user-images.githubusercontent.com/1012254/27931292-b878157a-6267-11e7-8f52-e7f1f53484fe.jpg)
