### ISSUE TITLE
Make sure survey banner doesn't violate CLS scores

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4466]
The current survey banner causes CLS issues. 

We should fix this.

**Comment by nainar** [comment]
Reopening because this is a fundamental issue with the way the banner is implemented. This issue will persist next quarter when we bring the survey back.

**Comment by matthiasrohmer** [comment]
Thanks for bringing this up! When Sebastian and I were implementing the banner we thought that having the banner dismissible is bigger UX win than what we lose by the CLS... but we both weren't really happy how it's built since we are abusing the `.amp-active` CSS class.

Any advise on how to proceed would be much appreciated 🙂

**Comment by patrickkettner** [comment]
@kevinkimball would you be able to weigh in on a better pattern to use for a dismiss-able banner?

**Comment by kevinkimball** [comment]
@patrickkettner Since it's a notification and dismissable, could use a fixed position below the navigation bar? Not sure how desirable it would be from the UI perspective but it would resolve the layout shift issue
