### ISSUE TITLE
Pixi: We should cache successful results

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4529]
We should cache results if all the tests finished. This allows users to rerun if a test failed.

**Comment by matthiasrohmer** [comment]
A few questions on this: what exactly do we want to cache and where? As an example: I am testing a page, all tests finish successfully except for Mobile Friendliness (might be due to a page being indeed unfriendly or because of technical API problems) for example. When I now press "Analyze" again what should happen? Should only the Mobile Friendliness check be rerun?

**Comment by matthiasrohmer** [comment]
I think this is related: https://github.com/ampproject/amp.dev/issues/4473#issuecomment-690282787

**Comment by nainar** [comment]
Oh yeah I should have been clearer - we should only cache a successful test result - where everything passes. 

And if we do that, we can prevent us going over our query limit for services we are using.

**Comment by matthiasrohmer** [comment]
Thanks for the clarification! I think we need to add a hint then to the lab results though to avoid having someone developing against Pixi and not seeing any improvements.

**Comment by nainar** [comment]
Oh yeah I guess we should cache the additional checks and field data only - not the lab results.
