### ISSUE TITLE
Pixi status banner not shown in ar version

### ISSUE THREAD

**Issue by tharders** [ampproject/amp.dev#4818]
When checking a page in the AR version of pixi the status banner is not shown.
https://amp-dev-staging.appspot.com/ar/page-experience/

![image](https://user-images.githubusercontent.com/6458408/95420567-f69ae980-093b-11eb-8d2f-117140ba7cb7.png)

I have checked different pages with different status results.
In an other language this works fine.
Maybe it is an LTR issue.

**Comment by patrickkettner** [comment]
it doesn't appear that the amp-script is ever being loaded. The blob is not in chrome's devtools as a context option, and none of the code in it appears to be running.

**Comment by patrickkettner** [comment]
this seems like potentially an issue with worker-dom?

@kristoferbaxter I stepped through the code, and in the version @tharders linked, we are hitting [this](https://github.com/ampproject/worker-dom/blob/1d4762aff3591f39f2f40bf7153a95ee0a48c7a1/src/main-thread/worker.ts#L104) post, but [the handler](https://github.com/ampproject/worker-dom/blob/1d4762aff3591f39f2f40bf7153a95ee0a48c7a1/src/main-thread/install.ts#L64) is never being entered.

**Comment by nainar** [comment]
Pinging @kristoferbaxter and @samouri

**Comment by samouri** [comment]
I don't see any issue with `worker-dom`. Running amp.dev locally and root caused the issue to be the translation itself. We are relying upon the `type` to be success or error in order to apply a necessary class:

https://github.com/ampproject/amp.dev/blob/90b488a8271ce07edec6abda234131814889300c/pixi/src/ui/StatusIntroView.js#L27-L30

For Arabic, it seems like the `type` is set to `نجاح`. This problem exists in other languages too, for example French.

Potential fixes:
1. Rely upon the ID of the returned status as opposed to `type`
2. Don't translate the type. I don't know if it is used in translated form elsewhere.

**Comment by patrickkettner** [comment]
Thanks for tracking this down, @samouri!
