### ISSUE TITLE
Server Side User Consent example is broken

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4910]
This refers to [this `amp-consent` example](https://amp.dev/documentation/examples/user-consent/server_side_user_consent_flow/?format=websites). Trying this in the playground, you just see a blank page.

One problem is the typo here:

`"checkConsentHref": "/documentation/examples/api/get-consent-sever-side"`

Even when we spell "server" correctly, though, it still doesn't display anything. I need to review `amp-consent` to see why this is.

**Comment by micajuine-ho** [comment]
With the correct spelling of `"checkConsentHref": "/documentation/examples/api/get-consent-server-side"`, we get a response from the endpoint, however returned JSON has neither a `consentRequired` nor a `promptIfUnknown` (legacy) field. 


To fix this, the endpoint's JSON needs to include `"consentRequired":true`.

Additionally, the <script> within the amp-consent element needs to include:  `"promptUI": "myConsentFlow"`, so that when consent is required, it will show the prompt. 

The example could further be expanded by adding an `<amp-ad data-block-on-consent>` on the page; it would only load once the user grants consent via the prompt that is shown.

**Comment by morsssss** [comment]
At least for me, that JSON did contain `"consentRequired":true`. Yay! However, you're right, the `promptUI` field was missing.  Adding it in there and fixing the typo made things work.

I wonder if this example was never tested....

See https://github.com/ampproject/amp.dev/pull/4966
