### ISSUE TITLE
Adding StorifyMe to amp.dev tools

### ISSUE THREAD

**Issue by nemanjapopovic** [ampproject/amp.dev#4947]
### Story creation resource name

StorifyMe

### Type

Use [x] to mark a selection:

- [X] Story Creation Tool
- [ ] CMS
- [ ] Platform
- [ ] Other

### URL

https://storifyme.com/

### Image

![image](https://user-images.githubusercontent.com/10596672/98372484-207c2480-203e-11eb-9614-d7219df6e7a9.png)

### Description

StorifyMe stands out as all-in-one Web Stories platform. Made for brands & individuals, tailored for e-commerce, marketers and publishers.

### List of Stories

https://storifyme.com/stories/storifyme-stories/top-10-lakes-in-canada-30673/amp
https://storifyme.com/stories/storifyme-stories/best-quotes-from-money-heist-43039/amp
https://storifyme.com/stories/storifyme-stories/teriyaki-chicken-with-only-3-ingredients-103187/amp
https://storifyme.com/stories/storifyme-stories/5-powerful-ingredients-for-eye-rejuvenation-30128/amp
https://storifyme.com/stories/storifyme-stories/ny-city-guide-for-2021-33395/amp
https://storifyme.com/stories/storifyme-stories/perfect-places-to-escape-from-new-york-this-weekend-39059/amp
https://storifyme.com/stories/storifyme-stories/hot-fire-flames-upper-body-workout-80795/amp
https://storifyme.com/stories/storifyme-stories/how-to-improve-your-mental-health-33137/amp
https://storifyme.com/stories/storifyme-stories/new-trendy-fashion-statement-for-2021-86779/amp
https://storifyme.com/stories/storifyme-stories/fashion-magazine-for-20212022-60253/amp

**Comment by matthiasrohmer** [comment]
@shishirm, may I ask you to review? 😉

**Comment by nemanjapopovic** [comment]
Hi @shishirm , any update regarding this or is there anything additional we need to provide? :)

**Comment by shishirm** [comment]
Hello,

Thanks so much for filing this issue. Given this is Thanksgiving week and most folks are OOO, we'll start reviewing next week and will attempt to complete by the end of next week. We'll reach out with any clarifying questions or changes requested. Apologies for the delay here!

Thanks again!

**Comment by nemanjapopovic** [comment]
Hi @shishirm , thank you for letting me know :). @sdenaro looking forward to your feedback :) 

Enjoy holidays and talk to you soon :)

**Comment by sdenaro** [comment]
I went over the stories, there are a few issues that seem to be universal:

### Errors

1. linkrelcanonicalisok

The connnical URL is incorecct, if doesn't include 'amp' even though the URLs provided do use amp.

Please ensure that the connnical URL is used for the stories and edit the submission to remove th trailing /amp

actual: https://storifyme.com/stories/storifyme-stories/fashion-magazine-for-20212022-60253,
expected: https://storifyme.com/stories/storifyme-stories/fashion-magazine-for-20212022-60253/amp

2. This story has a failing issue on image posters

https://storifyme.com/stories/storifyme-stories/fashion-magazine-for-20212022-60253/amp	

##### Video poster

storymetadatathumbnailsareok (FAIL)

  [poster-square-src = {""url"":""https://cdn.storifyme.com/accounts/storifyme-stories/images/22591/696x696/poster.png?1604676961393"",""width"":696,""height"":696,""mime"":""image/png""}] failed [isAtLeast928x928]

storymetadatathumbnailsareok (FAIL)

  [poster-landscape-src = {""url"":""https://cdn.storifyme.com/accounts/storifyme-stories/images/22591/928x696/poster.png?1604676961393"",""width"":696,""height"":696,""mime"":""image/png""}] failed [isLandscape, isAtLeast928x696]

##### Video sizing

[https://cdn.storifyme.com/accounts/templates/assets/f-1604671821777.qt,https://cdn.storifyme.com/accounts/templates/assets/f-1604672177040.qt]


### Warnings

1. Preload runtime 

Please use rel=preload when loading the runtime. 

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

2. video tag

Use <amp-video><source/></amp-video> instead of <amp-video src> 


3. Aspect ratios


4. Videos over 4MB

This is an AMP validation error, you should aim to use smaller videos when possible.

https://player.vimeo.com/external/408412129.hd.mp4?s=0dc8c5e810d75a1e02e8fc908cb199be129260d3&profile_id=174&oauth2_token_id=57447761,https://player.vimeo.com/external/387099146.hd.mp4?s=3c16edd1bd4e808684449d066f61e0bfacff1127&profile_id=174&oauth2_token_id=57447761

We have new guidance here on videos here:

https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/#video

* Shot for high end mobile devices
* Shot at 480p.
* Shot in at least 24 frames per second.
* Aim for videos shorter than 15 seconds and if longer break up into multiple videos.

5. Use bookends when possible

  <amp-story-bookend> 

None of the stories utilize this. 

### Issues with individual stories 

1.   https://storifyme.com/stories/storifyme-stories/top-10-lakes-in-canada-30673/amp

##### Aspect Ratios

ampimgheightwidthisok (WARN)
  [https://cdn.storifyme.com/accounts/templates/assets/f-1603724091115.jpeg]: actual ratio [800/600 = 1.33] does not match specified [3372/3468 = 0.97]

ampimgheightwidthisok (WARN)
  [https://cdn.storifyme.com/accounts/templates/assets/f-1603724091385.jpeg]: actual ratio [800/600 = 1.33] does not match specified [3372/3468 = 0.97]

ampimgheightwidthisok (WARN)
  [https://cdn.storifyme.com/accounts/templates/assets/f-1603724091109.jpeg]: actual ratio [800/600 = 1.33] does not match specified [2560/3840 = 0.66]

ampimgheightwidthisok (WARN)
  [https://cdn.storifyme.com/accounts/templates/assets/f-1603724091239.jpeg]: actual ratio [800/600 = 1.33] does not match specified [5751/3834 = 1.5]

ampimgheightwidthisok (WARN)
  [https://cdn.storifyme.com/accounts/templates/assets/f-1603724091248.jpeg]: actual ratio [800/600 = 1.33] does not match specified [5751/3834 = 1.5]

ampimgheightwidthisok (WARN)
  [https://cdn.storifyme.com/accounts/templates/assets/f-1603724091280.jpeg]: actual ratio [800/600 = 1.33] does not match specified [2560/3840 = 0.66]

ampimgheightwidthisok (WARN)
  [https://cdn.storifyme.com/accounts/templates/assets/f-1603724091247.jpeg]: actual ratio [800/600 = 1.33] does not match specified [3372/3468 = 0.97]

ampimgheightwidthisok (WARN)
  [https://cdn.storifyme.com/accounts/templates/assets/f-1603724091276.jpeg]: actual ratio [800/600 = 1.33] does not match specified [5751/3834 = 1.5]

ampimgheightwidthisok (WARN)
  [https://cdn.storifyme.com/accounts/templates/assets/f-1603724091425.jpeg]: actual ratio [800/600 = 1.33] does not match specified [3372/3468 = 0.97]

ampimgheightwidthisok (WARN)
  [https://cdn.storifyme.com/accounts/templates/assets/f-1603724091425.jpeg]: actual ratio [800/600 = 1.33] does not match specified [2991/3744 = 0.79]
ampvideoisspecifiedbyattribute (WARN)
  <amp-video src> used instead of <amp-video><source/></amp-video>

2. https://storifyme.com/stories/storifyme-stories/teriyaki-chicken-with-only-3-ingredients-103187/amp

##### Aspect Ratios

ampimgheightwidthisok (WARN)
  [https://cdn.storifyme.com/accounts/templates/assets/f-1604055466454.jpeg]: actual dimensions [750x1125] are much smaller than specified [1600x2400]

ampimgheightwidthisok (WARN)
[https://media3.giphy.com/media/hvd7mliQMHBhJepGd3/giphy.gif?cid=9a52f974esx5k8rh1xdsefkrxtq0ta49cqil7njia04zu8aq&rid=giphy.gif]: actual ratio [480/78 = 6.15] does not match specified [400/400 = 1]

ampimgheightwidthisok (WARN)
[https://media0.giphy.com/media/TgMzjXJqvaydmhBLUA/giphy.gif?cid=9a52f974z60t0axlqfdi0jhrvqy572r8atzk1sks5ttvf51b&rid=giphy.gif]: actual ratio [480/360 = 1.33] does not match specified [400/400 = 1]

##### Video size

ampvideoissmall (FAIL)
  videos over 4MB: [https://cdn.storifyme.com/accounts/templates/assets/f-1604050873523.mp4]

3. https://storifyme.com/stories/storifyme-stories/5-powerful-ingredients-for-eye-rejuvenation-30128/amp

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1541487574592-ffea5bce6106?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x720] are much smaller than specified [6240x4160]

ampvideoissmall (FAIL)
  videos over 4MB: [https://player.vimeo.com/external/369271637.hd.mp4?s=16843830e94f2eead0f7116238f5db7531e80056&profile_id=175&oauth2_token_id=57447761]

4.  https://storifyme.com/stories/storifyme-stories/ny-city-guide-for-2021-33395/amp

##### Image sizing issues

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1502899576159-f224dc2349fa?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x1350] are much smaller than specified [4000x5000]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1534800891164-a1d96b5114e7?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x1367] are much smaller than specified [4000x5062]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1508867743401-21ad68d105b1?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x1350] are much smaller than specified [3934x4918]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1512315342380-81f12a02bd7e?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x1354] are much smaller than specified [2025x2538]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x720] are much smaller than specified [5233x3489]

##### Video size

ampvideoissmall (FAIL)

  videos over 4MB: [https://player.vimeo.com/external/370845105.hd.mp4?s=1facf7310d1f043ea079556373d0618003593f2d&profile_id=171&oauth2_token_id=57447761,https://player.vimeo.com/external/438476876.hd.mp4?s=7833dd06cf5597c3bd13927baacf2916dea66bc4&profile_id=175&oauth2_token_id=57447761]

5. 
https://storifyme.com/stories/storifyme-stories/perfect-places-to-escape-from-new-york-this-weekend-39059/amp	

##### Video size

  videos over 4MB: [https://player.vimeo.com/external/456595431.hd.mp4?s=7f0c675f7f59b989c10cfd5a918789a1e482065c&profile_id=175&oauth2_token_id=57447761,https://player.vimeo.com/external/435559747.hd.mp4?s=d948da4712b88a0c7862c29c372faedb8ebb7c97&profile_id=175&oauth2_token_id=57447761]


6. 
https://storifyme.com/stories/storifyme-stories/hot-fire-flames-upper-body-workout-80795/amp	

##### Image sizing issues

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1434682881908-b43d0467b798?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x717] are much smaller than specified [3908x2595]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1434847868581-86e8a2b8e7a3?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x717] are much smaller than specified [4190x2782]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1434682881908-b43d0467b798?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x717] are much smaller than specified [3908x2595]


7. https://storifyme.com/stories/storifyme-stories/how-to-improve-your-mental-health-33137/amp	

##### Image sizing issues

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1590225472433-e20c5d118c60?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x811] are much smaller than specified [5328x4000]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1567111089028-9abb29aa1102?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x1440] are much smaller than specified [3024x4032]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1596570759609-d8e9f2aa204e?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x1620] are much smaller than specified [3441x5162]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1528144247106-ed7ed4c468c3?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x1440] are much smaller than specified [3024x4032]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1520013817300-1f4c1cb245ef?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x686] are much smaller than specified [7340x4665]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1516824711718-9c1e683412ac?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x720] are much smaller than specified [5915x3943]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1535556116002-6281ff3e9f36?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x1125] are much smaller than specified [2572x2678]

ampimgheightwidthisok (WARN)
[https://images.unsplash.com/photo-1569690681342-d74eb25436fd?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjk0NTU0fQ]: actual dimensions [1080x720] are much smaller than specified [5568x3712]

##### Video sizing 

ampvideoissmall (FAIL)

  videos over 4MB: [https://player.vimeo.com/external/392021778.hd.mp4?s=0ca8c46a55287f026fee7334868b33926487a94b&profile_id=170&oauth2_token_id=57447761,https://player.vimeo.com/external/428268149.hd.mp4?s=1ed833040c87ffd22853d4fdbdb79eb46e75b663&profile_id=174&oauth2_token_id=57447761]

**Comment by nemanjapopovic** [comment]
Hey @sdenaro thank you so much for such a detailed report. We will jump on updating/fixing these things right away. In the meantime, can you please let us know what tool did you use for validation so we can check that it works as expected before we ping you here again?

**Comment by sdenaro** [comment]
@nemanjapopovic 

I will be using the amp-linter to verify

https://github.com/ampproject/amp-toolbox/tree/main/packages/linter

Thanks

**Comment by MiselKING** [comment]
Hi @sdenaro , we updated our stories and fixed all errors and warnings mentioned in your previous review.
Can you please review again and let us know if everything is working as expected (or if there is anything else we should fix)?

Thanks

**Comment by sdenaro** [comment]
@MiselKING @nemanjapopovic I will confirm your changes on Monday. If everything is ok, the PR should be in by end of day Monday or early Tuesday at the latest.

Thanks.

**Comment by nemanjapopovic** [comment]
Hey @sdenaro, thank you so much for letting us know, have a great rest of the weekend, and talk to you soon.

**Comment by sdenaro** [comment]
@MiselKING  @nemanjapopovic look like all the issues are resolved, I'm going to work on the PR today. thanks

**Comment by nemanjapopovic** [comment]
Hey @sdenaro , great news, thank you so much for checking it again and working on it :)

**Comment by sdenaro** [comment]
@nemanjapopovic  https://github.com/ampproject/amp.dev/pull/5086
