### ISSUE TITLE
Adding Unfold to amp.dev tools

### ISSUE THREAD

**Issue by avarghese-sqsp** [ampproject/amp.dev#4970]
### Story creation resource name

Unfold

### Type

Use [x] to mark a selection:

- [] Story Creation Tool
- [ ] CMS
- [x] Platform
- [ ] Other

### URL

https://unfold.com/

### Image
![Unfold_GoogleWebStories](https://user-images.githubusercontent.com/59689485/99283536-0c4dd980-282d-11eb-9774-d5403963b64e.png)

### Description

Unfold helps brands and individuals easily create beautiful stories with templates. 

### List of Stories

1. https://stori.es/Yjy4P
2. https://stori.es/pAwoy 
3. https://stori.es/9KAgr 
4. https://stori.es/pzm8D 
5. https://stori.es/2w1ox 
6. https://stori.es/pwDZy 
7. https://stori.es/rGpMd 
8. https://stori.es/XdXD6 
9. https://stori.es/3d5pw 
10. https://stori.es/w5nbp

**Comment by sdenaro** [comment]
I can take this one.

**Comment by shishirm** [comment]
Hello,

Thanks so much for filing this issue. Given this is Thanksgiving week and most folks are OOO, we'll start reviewing next week and will attempt to complete by the end of next week. We'll reach out with any clarifying questions or changes requested.

Thanks again!

**Comment by sdenaro** [comment]
#### Need to Fix

All ten stories have issued with video that is over the3 4mb limit, leading it to be considered problematic for AMP. They also have issues with the story metadata thumbnails. These are critical for search results.


1. https://stori.es/Yjy4P

ampvideoissmall (FAIL)

  videos over 4MB: [https://cdn-stories.unfold.com/Y/j/Yjy4P/c48d38dd-b230-4047-8165-cd228ff905a7/a78d823b-5e7b-4fb9-87c2-574c91bd5659.mov,https://cdn-stories.unfold.com/Y/j/Yjy4P/c48d38dd-b230-4047-8165-cd228ff905a7/c6933d93-1af2-4062-9b57-208c05df82e9.mov]

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {""url"":""https://cdn-stories.unfold.com/Y/j/Yjy4P/c48d38dd-b230-4047-8165-cd228ff905a7/3ba7e84b-3f57-49e1-afb7-1e1696468341.jpg"",""width"":1080,""height"":1920,""mime"":""image/jpeg""}] failed [isPortrait]


2. https://stori.es/pAwoy

ampvideoissmall (FAIL)

  videos over 4MB: [https://cdn-stories.unfold.com/p/A/pAwoy/5cc1c301-c945-4ce6-9473-861d6792e2dd/0c34774d-9148-4992-9e03-30d60d073806.mov]

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {""url"":""https://cdn-stories.unfold.com/p/A/pAwoy/5cc1c301-c945-4ce6-9473-861d6792e2dd/ce8142b5-f283-446d-9174-3b3b90f98960.jpg"",""width"":1080,""height"":1350,""mime"":""image/jpeg""}] failed [isPortrait]

3. https://stori.es/9KAgr

ampvideoissmall (FAIL)

  videos over 4MB: [https://cdn-stories.unfold.com/9/K/9KAgr/c82f3a74-02f4-4ca9-91e1-ff710b12c368/ed706d13-7391-4244-9bc8-6c29e3c704f1.mov,https://cdn-stories.unfold.com/9/K/9KAgr/c82f3a74-02f4-4ca9-91e1-ff710b12c368/5260c702-f926-42bb-aafd-dfc143e85f63.mov]

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {""url"":""https://cdn-stories.unfold.com/9/K/9KAgr/c82f3a74-02f4-4ca9-91e1-ff710b12c368/9bb6811e-dcd7-4264-91cb-22a4d56c7752.jpg"",""width"":1080,""height"":1920,""mime"":""image/jpeg""}] failed [isPortrait]

4. https://stori.es/pzm8D

ampvideoissmall (FAIL)

  videos over 4MB: [https://cdn-stories.unfold.com/p/z/pzm8D/123c61f3-8c41-417c-a41c-50ae27540edc/7753dd04-f260-47b6-a1ff-17459f37ae2a.mov,https://cdn-stories.unfold.com/p/z/pzm8D/123c61f3-8c41-417c-a41c-50ae27540edc/32fadfec-b65c-4b6e-a965-0d9916c84b96.mov]

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {""url"":""https://cdn-stories.unfold.com/p/z/pzm8D/123c61f3-8c41-417c-a41c-50ae27540edc/ad7d11ac-943a-4685-8453-a37de58cec95.jpg"",""width"":1080,""height"":1920,""mime"":""image/jpeg""}] failed [isPortrait]

5. https://stori.es/2w1ox

ampvideoissmall (FAIL)

  videos over 4MB: [https://cdn-stories.unfold.com/2/w/2w1ox/6e964447-3b35-4772-8270-ee5e19e4d6a0/ff3f3c43-1948-4d78-af00-97440460d768.mov,https://cdn-stories.unfold.com/2/w/2w1ox/6e964447-3b35-4772-8270-ee5e19e4d6a0/a7a0dd96-db1f-4d80-bd63-994570831e2e.mov]

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {""url"":""https://cdn-stories.unfold.com/2/w/2w1ox/6e964447-3b35-4772-8270-ee5e19e4d6a0/6f6fc8f3-9d03-4b0d-9ec1-ae2ce307c39c.jpg"",""width"":1280,""height"":1920,""mime"":""image/jpeg""}] failed [isPortrait]

6. https://stori.es/pwDZy	

ampvideoissmall (FAIL)

  videos over 4MB: [https://cdn-stories.unfold.com/p/w/pwDZy/afbb1439-3720-48c6-96fe-53be7c1a175a/f4690f37-e979-429b-ae69-f3e7ffcc4e2c.mov,https://cdn-stories.unfold.com/p/w/pwDZy/afbb1439-3720-48c6-96fe-53be7c1a175a/d38d65b2-1b6a-4005-9612-ea897de27a6e.mov]

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {""url"":""https://cdn-stories.unfold.com/p/w/pwDZy/afbb1439-3720-48c6-96fe-53be7c1a175a/02f0fffd-7786-4680-9cf1-a5bfa5296148.jpg"",""width"":1280,""height"":1920,""mime"":""image/jpeg""}] failed [isPortrait]

7. https://stori.es/rGpMd	

ampvideoissmall (FAIL)

  videos over 4MB: [https://cdn-stories.unfold.com/r/G/rGpMd/1bb47472-281c-473c-ade4-1f8781b2eb2a/471d59c5-156b-469f-bb28-2bb60460071a.mov,https://cdn-stories.unfold.com/r/G/rGpMd/1bb47472-281c-473c-ade4-1f8781b2eb2a/e16799e2-e735-458e-a029-dcb877bdf8da.mov]

8. https://stori.es/XdXD6  

ampvideoissmall (FAIL)

  videos over 4MB: [https://cdn-stories.unfold.com/X/d/XdXD6/aa4437c9-947c-49b9-afd6-29bf3b0dc51c/13e0fb3f-5888-4e1d-a16e-c972ff4bf289.mov,https://cdn-stories.unfold.com/X/d/XdXD6/aa4437c9-947c-49b9-afd6-29bf3b0dc51c/991c5f79-dca5-4d71-a077-1bc90407b3a6.mov]

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {""url"":""https://cdn-stories.unfold.com/X/d/XdXD6/aa4437c9-947c-49b9-afd6-29bf3b0dc51c/a793c179-5d76-4f36-8f5e-8a68e4270ee6.jpg"",""width"":1280,""height"":1920,""mime"":""image/jpeg""}] failed [isPortrait]

9. https://stori.es/3d5pw  

ampvideoissmall (FAIL)

  videos over 4MB: [https://cdn-stories.unfold.com/3/d/3d5pw/de20c6ca-31ba-4e43-9f8c-e020be68b45b/d166de29-3552-40d6-a5dc-5e4bb7b37b3d.mov,https://cdn-stories.unfold.com/3/d/3d5pw/de20c6ca-31ba-4e43-9f8c-e020be68b45b/404d75a2-3fa5-4afd-85b8-b3f024d7340f.mov]

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {""url"":""https://cdn-stories.unfold.com/3/d/3d5pw/de20c6ca-31ba-4e43-9f8c-e020be68b45b/0adf43b3-385b-4d3f-a164-325793438172.jpg"",""width"":1280,""height"":1920,""mime"":""image/jpeg""}] failed [isPortrait]

10.  https://stori.es/w5nbp	
ampvideoissmall (FAIL)

  videos over 4MB: [https://cdn-stories.unfold.com/w/5/w5nbp/17b569cd-8aff-4e38-9991-40b13b78af40/b04545be-1384-4a0b-8c3d-6ba62c1c26df.mov,https://cdn-stories.unfold.com/w/5/w5nbp/17b569cd-8aff-4e38-9991-40b13b78af40/c65a8136-e199-4011-a27d-40881750fc17.mov]

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {""url"":""https://cdn-stories.unfold.com/w/5/w5nbp/17b569cd-8aff-4e38-9991-40b13b78af40/b897b400-4692-4595-90e7-50641f05252a.jpg"",""width"":1280,""height"":1920,""mime"":""image/jpeg""}] failed [isPortrait]
"
#### Nice to Have

1. video tag

Use `<amp-video><source/></amp-video>` instead of `<amp-video src>`

2. Videos over 4MB

This is an AMP validation error, you should aim to use smaller videos when possible.

We have new guidance here on videos here:

https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/#video

* Shot for high end mobile devices
* Shot at 480p.
* Shot in at least 24 frames per second.
* Aim for videos shorter than 15 seconds and if longer break up into multiple videos.

3. Use bookends when possible

`  <amp-story-bookend>`

None of the stories utilize this.

**Comment by avarghese-sqsp** [comment]
Thanks @sdenaro for the feedback. We will work on updating the stories with smaller videos and other recommendations

**Comment by sdenaro** [comment]
@avarghese-sqsp Any new word? Let me know if you need anything from our end.

**Comment by sdenaro** [comment]
@avarghese-sqsp  just checking in. is there anything you need from my side?

**Comment by patrickkettner** [comment]
closing for the time being, @avarghese-sqsp please comment if you would like it to be reopened in the future, or feel free to submit a new issue

best!
patrick

**Comment by avarghese-sqsp** [comment]
Due to current project priorities, we won't be able to work the requested changes. When we circle back on this in future, we will submit a new issue.

**Comment by sdenaro** [comment]
@avarghese-sqsp I will be working on the PR today.
