### ISSUE TITLE
Amp4Email: amp-autocomplete-email component not working

### ISSUE THREAD

**Issue by anbarasiu** [ampproject/amp.dev#5146]
## 🐛 Bug Report

I'm following the documentation [here](https://amp.dev/documentation/examples/components/amp-autocomplete-email/), but the amp-autocomplete-email isn't working, even after importing the required amp-autocomplete component.

I tried to open the demo on [playground](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-autocomplete-email&format=email&_gl=1*ix9bcx*_ga*YW1wLWNaX0tpMkg1ZmFwWHhuOU5DbDI1SWc.) on the same doc page, which throws this error in the console. 
`Resource: failed to build: amp-autocomplete#1: <amp-autocomplete> is not currently available in AMP4Email.`

This is misleading, since the documentation states that the component is available.

**Comment by caroqliu** [comment]
@sebastianbenz @matthiasrohmer Would it be possible to inject `data-amp-autocomplete-opt-in` attribute to `amp-autocomplete` elements displayed in the AMP playground in the email format? This is a partially-supported feature in email -- valid to send in emails, but off by default when viewing emails. Individual email clients can turn it on by default in their environments when they add support by injecting the above attribute at runtime, so it would be helpful if the AMP playground replicated a supported environment behavior rather than an unsupported one.

**Comment by patrickkettner** [comment]
yep! PRed a change - thanks @caroqliu!!

**Comment by caroqliu** [comment]
thank you!!

**Comment by patrickkettner** [comment]
this was fixed by #5165
