### ISSUE TITLE
Whitelabeling of a an already existing AMP module.

### ISSUE THREAD

**Issue by Sovica** [ampproject/amp.dev#5147]
We have an AMP module published already, this one - https://amp.dev/documentation/examples/components/amp-brid-player/ but due to the way we work and have Whitelabel customers, our users are looking for a way to Whitelabel these AMP embed codes to point to different URL's.

For example HEAD:
<script async custom-element="amp-brid-player" src="https://cdn.ampproject.org/v0/amp-brid-player-0.1.js"></script>
To:
<script async custom-element="amp-whitelabel-player" src="https://cdn.ampproject.org/v0/amp-whitelabel-player-0.1.js"></script>

Is there some possibility of doing this without our users going through the entire submission process of a new AMP module?

**Comment by patrickkettner** [comment]
Hi @Sovica!
They can use your version of the component, but in order for it to be considered valid AMP they would need to be an official component or written using [amp-script](https://amp.dev/documentation/components/amp-script/)

For future reference, ampproject/amphtml would be the best place to ask questions about the library (rather than questions about the amp.dev site)
