### ISSUE TITLE
boilerplate feature is not working with firefox latest releases > 80

### ISSUE THREAD

**Issue by e-struct** [ampproject/amp.dev#5315]
FYI 
boilerplate feature is not working with firefox latests releases
OS:
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch

**Comment by sebastianbenz** [comment]
what do you mean by boilerplate feature?

**Comment by e-struct** [comment]
The boilerplate available on that page works fine on Chromium but not 
Firefox!

https://amp.dev/boilerplate/


Le 08/02/2021 à 13:10, Sebastian Benz a écrit :

**Comment by patrickkettner** [comment]
@e-struct I am able to interact with the boilerplate builder you linked to on ubuntu 16.04.06 firefox, with the latest stable updates. Due to it working there, as well as all other browsers I have checked, I am inclined to think this is a browser bug rather than a library one. 
Would you be able to explain what is not working explicitly? What is or is not happening?

**Comment by patrickkettner** [comment]
Closing due to lack of replication, but @e-struct please do comment if you are able to elaborate on the issue!
