### ISSUE TITLE
Pixi: Transform hero images advice given even when there is no amp-img in first viewport

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#5416]
## 🐛 Bug Report

On https://amp-wp.org we do not have any `amp-img` in the first viewport. All images are inline as SVGs. Nevertheless, doing a PX Guide check results in the “Transform hero images on the page” advice being given:

![image](https://user-images.githubusercontent.com/134745/108760128-1b19eb80-7502-11eb-914d-5821075b2fff.png)

### Current behavior

Advice is given

### Expected behavior/code

Advice should not be given since not appropriate

**Comment by sebastianbenz** [comment]
That's tricky. If I remember correctly, the check uses the same algorithm as AMP Optimizer to identify hero images. The problem is that there's no good way to identify an hero image without rendering the page. 

My only idea would be to add a sentence: "Please ignore this advice if you don't display images in the first viewport".

**Comment by westonruter** [comment]
Yes, I see the [`HeroImageIsDefined`](https://github.com/ampproject/amp-toolbox/blob/f23b914bd629e9dc29afd865517626f04e57b490/packages/linter/src/rules/HeroImageIsDefined.ts) rule is using the `PreloadHeroImage` transformer.

Adding that sentence would be a quick fix.
