### ISSUE TITLE
1st breadcrumb is always in English, not translated

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amp.dev#545]
If there are children in the breadcrumb, the primary ancestor (the 1st breadcrumb) appears in English, no matter the selected language.  Even if it's a `breadcrumb` variable, like in [overview.yaml](https://github.com/ampproject/docs/blob/master/content/learn/overview.yaml#L3) or not, like in [support.md](https://raw.githubusercontent.com/ampproject/docs/master/content/support/support.md).

Discussed and related to: #501

**Comment by bpaduch** [comment]
Appears to no longer be an issue:

- Indonesia page - https://www.ampproject.org/id/learn/who-uses-amp/ad-tech-platforms/
- Spanish page
 - https://www.ampproject.org/es/learn/who-uses-amp/ad-tech-platforms/
- https://www.ampproject.org/es/case-studies/publishers/

**Comment by dereklewis** [comment]
@bpaduch I believe the FAQ pages are still affected. For example, see: https://www.ampproject.org/es/support/faqs/overview

**Comment by bpaduch** [comment]
@dereklewis - What was wrong with the initial way of using breadcrumbs, back in this [commit](https://github.com/ampproject/docs/commit/c9a57865b3a484cbecf955ab5a70d687cfdacdd2).  It actually worked correctly, that is links work, and the localized text appears.

**Comment by bpaduch** [comment]
@dereklewis - ping.

**Comment by dereklewis** [comment]
@bpaduch That method of implementing breadcrumbs fits one use-case (max 3 breadcrumbs) and is not extensible as @pbakaus and I agreed when I brought it up to him at AMP Conf. Essentially, hard-coding each ancestor, as opposed to iterating, is preventing it from scaling gracefully. If you can provide me with a peer-reviewed UX study that claims greater than 3 breadcrumbs results in poor UX, I would gladly stand corrected. :)

**Comment by bpaduch** [comment]
I agree that hard-coding is never better than extensibility. If we can fix this issue in a timely manner to accommodate our non-English readers, that'd be great.

In terms of number of breadcrumbs, we will not have more than 3 breadcrumbs, because breadcrumbs are tied to menu levels, and to more than 3-levels of menu navigation isn't user friendly - poor discovery of information and users can get lost in clicking levels.  I'm not a UX expert but I do want our users to easily find information.   Paul (@pbakaus) might be able to chime in on this.

In the end, correcting this issue with extensible code is ideal.  Just would like it soon. ;)

**Comment by dereklewis** [comment]
Fortunately for us, I finally have time to resolve this issue. My apologies for the delay.

The way I see it, whether or not we will ever use the additional ancestors seems like a moot point because, according to the [`README.md`](https://github.com/ampproject/docs/blob/master/README.md), "Even if you don't plan on contributing, explore how we've built the site for a good example of how to build a canonical, responsive standalone AMP site." To me, this means that this site's source should also serve as a resource to educate others on how to build an ideal AMP site; hence, my effort to make the breadcrumbs more robust.

Paul likely has higher priorities to attend to than this, but if you get a chance, you may want to take a quick peak at this page from a book we used last semester called "Don't Make Me Think, Revisited: A Common Sense Approach to Web Usability" by Steve Krug. I have seen conflicting opinions about hierarchy depth on blogs, but this is a revised and published book, which may or may not contribute to its credibility.

![Don't Make Me Think: Breadcrumbs](https://user-images.githubusercontent.com/17770407/31022944-64b1dfb4-a508-11e7-8b8b-c95475c9d1b2.png)
