### ISSUE TITLE
AMP Native Libraries showing as Unused JS / Third Party JS in Lighthouse and Page Speed Index.

### ISSUE THREAD

**Issue by vaibhav-readwhere** [ampproject/amp.dev#5505]
### Current behavior
AMP Native Libraries i.e v0.js, amp-analytics-0.1.js etc which are mandatory for error free AMP pages are showing as Unused JS / Third Party JS in Lightbox and Page Speed Index.

Please also provide:

<img width="768" alt="Screen Shot 2021-03-11 at 11 28 10 AM" src="https://user-images.githubusercontent.com/5145846/110742814-060cbe80-825d-11eb-9d42-3391f1c2b163.png">
<img width="755" alt="Screen Shot 2021-03-11 at 11 28 25 AM" src="https://user-images.githubusercontent.com/5145846/110742845-16249e00-825d-11eb-81fb-3da6632162b4.png">

### Expected behavior/code
These libraries are mandatory according to the AMP dev rules and ought to be used in every page, but lighthouse and PSI shows these libraries as unused or third party js which is adding to the page load. It would be great if we can find out a way of declaring them mandatory or optimising them.

### Reproduction procedure
You can reproduce it using below steps :

1. Take any AMP page.
2. Run a lighthouse or Page Speed Index test on the same.
3. Checkout Opportunities & Diagnostics sections for the detials.

- What browser are you using? - Chrome
- What O/S are you using? - MacOs

**Comment by matthiasrohmer** [comment]
Thanks a lot for taking your time to report this! This is the documentation repository for the AMPHTML framework. The code relevant for this issue is located at ampproject/amphtml.

This is also where this issue has been already discussed. See https://github.com/ampproject/amphtml/issues/28638#issuecomment-638277038 for a qualified response.

Closing since this is not an actual issue with the documentation. If the issue linked above doesn't answer your questions feel free to create a new one over at ampproject/amphtml.
